name: Host Service CI

on:
  push:
    branches: [ "main" ]
    paths: ["*.js"]

jobs:
  buildImage:
    runs-on: ubuntu-latest 
    steps:
    - name: 1. Checkout
      uses: actions/checkout@v3

    - name: 2. Login to Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: 3. Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: kongkomido/hostservice:${{ github.sha }}
  
  updateYaml:
    runs-on: ubuntu-latest
    needs: buildImage #업데이트yaml이 앞에가 성공해야 실행하도록
    steps:
    - name: 1. Checkout
      uses: actions/checkout@v3
      with:
        repository: 'kongkomido/hostsvc-cd'
        token: ${{ secrets.GITHAB_TOKEN }}
    - name: 2. Change Docker Tag
      run: |
        sed -i "s/image: kongkomido\/node-app:.*/images: kongkomido\/node-app:${{ github.sha }}/g" hostservice-deploy.yaml
        git config --global user.email "kongkomido@naver.com"
        git config --global user.name "KimYoonHyung"
        git commit -am "triggered by github action"
        git push origin main